name: Test KNP-EMI DG code
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: ["main"]
  push:
    branches: ["**"]

env:
  DEB_PYTHON_INSTALL_LAYOUT: deb_system

defaults:
  run:
    shell: bash -el {0}

jobs:
  test_scripts:
    runs-on: ubuntu-latest
    container: ubuntu:latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup conda-forge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: KNP-EMI
          python-version: "3.10"
          use-mamba: true
          environment-file: environment.yml

      - name: Run test (MMS)
        run: |
          python ./tests/run_MMS_space.py
