name: Test KNP-EMI code via docker
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: ["main"]
  push:
    branches: ["**"]

env:
  DEB_PYTHON_INSTALL_LAYOUT: deb_system

defaults:
  run:
    shell: bash -el {0}

jobs:
  test_scripts:
    runs-on: ubuntu-latest
    container: ghcr.io/scientificcomputing/fenics:2023-08-14
    # Use older DOLFIN image, due to ulfy using ufl directly

    steps:
      - uses: actions/checkout@v4

      - name: install package
        run: |
          python3 -m pip install .

      - name: Run test (MMS)
        run: |
          python3 ./src/run_MMS_space.py
